### ISSUE TITLE
Could you provide extractCDS.pl？

### ISSUE THREAD

**Issue by shimw6828** [patelhardip/koalaor#1]
Thank you very much for your work. Recently, I want to identify the OR gene. But I didn't find extractCDS.pl in this repository. Where can I get this script?
thank you

**Comment by hp2048** [comment]
Hi @shimw6828:
I have modified the readme file now. You don't need extractCDS.pl as it has been incorporated into the `ORFinder.pl` script.

Please use the following command and it should take care of everything.

```
perl koalaor/ORFinder.pl -reffasta /path/to/genome.fasta(.gz) -speciescode HUMAN -outputdir /path/to/output/directory -threads 6
```

Have a look at readme file too. Let me know if you run into problems.
Cheers

**Comment by shimw6828** [comment]
> Hi @shimw6828:
> I have modified the readme file now. You don't need extractCDS.pl as it has been incorporated into the `ORFinder.pl` script.
> 
> Please use the following command and it should take care of everything.
> 
> ```
> perl koalaor/ORFinder.pl -reffasta /path/to/genome.fasta(.gz) -speciescode HUMAN -outputdir /path/to/output/directory -threads 6
> ```
> 
> Have a look at readme file too. Let me know if you run into problems.
> Cheers

Thank you, I have another question. Could you tell me how to identify Pseudo-OR gene in your method?

**Comment by hp2048** [comment]
Hi @shimw6828
pseudo genes and partial genes would be labeled with a trailing P. Trailing F is for full length OR with predicted intact ORF. 
I hope this helps. 
Cheers

**Comment by shimw6828** [comment]
> Hi @shimw6828
> pseudo genes and partial genes would be labeled with a trailing P. Trailing F is for full length OR with predicted intact ORF.
> I hope this helps.
> Cheers

Thanks a million！！！
